on: push
name: CI
jobs:
  test:
    env:
      TESTCOVERAGE_THRESHOLD: 95
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: go test -v -coverprofile=coverage.out -covermode=atomic ./...
      - if: matrix.os == 'windows-latest'
        run:
          go test -b -cover ./...
      - name: upload coverage reports to CodeCov
        uses: codecov/codecov-action@v3
